### ISSUE TITLE
Properties are not generated in a consistent order for AllOf

### ISSUE THREAD

**Issue by Fresa** [corvus-dotnet/Corvus.JsonSchema#235]
A property that has a AllOf keyword gets it's property generated in seemingly random order.

Example:
```
foo:
  type: object
  allOf:
    - $ref: "#/bar"
    - type: object
       properties:
         baz:
           type: string
bar:
  type: object
  properties:
    qux:
      type: string

```
When generating `foo` This will generate a C# type `Foo` with properties `baz` and `qux`, but they will be generated in seemingly random order.

I've gone through some of the code generation code, I couldn't find anything obvious, but the [template that generates the properties](https://github.com/corvus-dotnet/Corvus.JsonSchema/blob/0642370ab4905920baf2acac2de57472874a7a3f/Solutions/Corvus.Json.CodeGeneration.202012/Corvus.Json.CodeGeneration.Draft202012/Generators/CodeGenerator.Properties.cs#L647) doesn't seem to explicitly decide an order. Wouldn't it make sense render the properties by name? I assume that would implicitly solve what ever is causing this issue.

I'm using the Draft202012 generator.
Corvus.Json.JsonSchema 1.0.14
Corvus.Json.ExtendedTypes 1.0.14
Corvus.Json.CodeGeneration.202012 1.0.14

**Comment by mwadams** [comment]
I agree - this is very annoying.

I propose to sort lexically by name to stabilise this.

**Comment by mwadams** [comment]
I have added this to our "property name typing" over on #212 

I had only occasionally hit this problem because I generally use the explicit parameter-naming feature of C# to make it clearer what is happening when I'm calling create - which happened to mitigate the re-ordering issue.

```csharp
 return Commit.Create(
     eventStreamId: this.Commit.EventStreamId,
     eventStreamType: this.Commit.EventStreamType,
     commitSequenceNumber: this.Commit.CommitSequenceNumber,
     lastEventSequenceNumber: nextEvent.SequenceNumber,
     events: this.Commit.Events.Add(nextEvent));
``` 

I strongly recommend using the explicit parameter naming in any existing codebase; you can then revert once you have updated to the stable ordering once this PR lands.

**Comment by Fresa** [comment]
That's good advice, I'm already doing it :) 

I have a PR check that detects drift between a schema and a generated type by automatically generate the type using the schema and check for git diffs, that doesn't work well when the generator isn't idempotent. Do you have any idea when you'll merge #212?

**Comment by mwadams** [comment]
It's merged and released. 

https://www.nuget.org/packages/Corvus.Json.JsonSchema.TypeGeneratorTool
