### ISSUE TITLE
CodeGeneration Draft 7 doesn't detect types embedded in a json document

### ISSUE THREAD

**Issue by Fresa** [corvus-dotnet/Corvus.JsonSchema#256]
Seems it's due to the [reference dropping the fragment](https://github.com/corvus-dotnet/Corvus.JsonSchema/blob/043305c752b64f027b49d080056ca8795127b66e/Solutions/Corvus.Json.CodeGeneration.7/Corvus.Json.CodeGeneration.Draft7/JsonSchemaBuilder.cs#L37) when generating type declarations. 

Tried to replace `rebase ? reference : reference.WithFragment(string.Empty)` with `reference`, it seems to work. Had a look in [Draft 2020-12 which doesn't have that condition statement](https://github.com/corvus-dotnet/Corvus.JsonSchema/blob/043305c752b64f027b49d080056ca8795127b66e/Solutions/Corvus.Json.CodeGeneration.202012/Corvus.Json.CodeGeneration.Draft202012/JsonSchemaBuilder.cs#L37).

**Comment by mwadams** [comment]
fixed in V2.0.0
