### ISSUE TITLE
Ability to rely entirely on dotnet dependencies without Corvus.Json.ExtendedTypes

### ISSUE THREAD

**Issue by xaviergxf** [corvus-dotnet/Corvus.JsonSchema#285]
Hello,

   When trying to use Corvus.JsonSchema library to generate DTOs in a large project on dotnet 8 i found some conflicts regarding extensions methods on IEnumerable. There are conflicts between System.Interactive (a dependency of a dependency of Corvus.Json.ExtendedTypes) and MoreLinq.
    Do you have any plans to support generating these DTOs without any external dependency outside of the target framework? An idea would be to choose the T4 template when use the CLI to generate this?
    What do you think? 

Thanks

**Comment by mwadams** [comment]
Apologies! I missed this when it first appeared.

Can you give me examples of the conflicts, and I can add them to the list of exclusions in the codegen.

**Comment by mwadams** [comment]
It seems that the reference to `Corvus.Extensions` is the issue here.

This dependency can be removed without issue.

**Comment by mwadams** [comment]
The PR addresses these collisions (by removing the transitive dependencies). 

It *does not* remove the dependency on Corvus.Json.ExtendedTypes which is essential to the generated code.
