### ISSUE TITLE
array properties within allOf directives are not merged

### ISSUE THREAD

**Issue by Fresa** [corvus-dotnet/Corvus.JsonSchema#301]
I found another `allOf` problem this time regarding arrays.

We have a property that is defined as an `allOf` of two schemas. These two schemas are pretty similar, except for some few properties. Both schemas contains a property with the same name, both defined as an array but with items from two different schemas. I can see that the array objects are generated as two different structures (not merged), and only one of them defines the property on the merged `allOf` object.

The allOf schema looks something like this:
```
allOf:
  - $ref: "./vehicle.yaml#/components/schemas/car"
  - $ref: "#/components/schemas/car"
```

./vehicle.yaml#/components/schemas/car:
```
type: object
properties: 
  wheels:
    type: array
    items:
      $ref: "#/components/schemas/wheel"
```

./vehicle.yaml#/components/schemas/wheel:
```
type: object
properties:
  size: 
    type: integer
```

#/components/schemas/car:
```
type: object
properties: 
  wheels:
    type: array
    items:
      $ref: "#/components/schemas/wheel"
```
#/components/schemas/wheel:
```
type: object
properties:
  size: 
    type: integer
  color: 
    type: string
```

The `wheels` schema of the first `car` schema in the `allOf` directive seems to be the one that get's referred to in the generated `car` class as the field type `Wheels`.

I believe the problem is that the two different array properties with the same name never get's merged into one object (and their item objects). 

Note: I haven't tested this example, but I think it's representable to the actual schema that I can't post.
Observed on 2.0.8.

**Comment by Fresa** [comment]
It seems both `wheel` schemas get's generated to two classes with the same dotnet type name (`Wheel.cs`), generated in a random order, so the last one being generated overwrites the first one when written to file.

**Comment by mwadams** [comment]
There are two things going on here.

1) Attempting to merge "allOf" where you have property definitions

2) File naming of the types emitted from the two schema

Dealing with `1` first - we don't make any attempt to merge the two different array items types; one of the two will win (and it should be consistent as to which of the two wins based on the changes we made to the property evaluation order. (I will check that and verify if we still have an instability on that particular use case, and fix if so.)

We make a "best effort" to merge the `allOf` elements together to present a sensible entity to the user, but composition of schema is actually quite hard. There is some interesting academic research which is looking at evaluating equivalence of JSON Schema, but it is not something that we are ready for yet!

However, when you have an entity with the "allOf" type, if you wish to treat an instance as one or the other of the `allOf` composed types, you can use the specialized `.AsXX` conversion accessors to cast to the desired type and use it in that way. These accessors are generated from the `allOf` definition and give you discoverability.

`2` is definitely a bug if they are actually being overwritten. The types should be nested into the parent schema, or get a suffix if they end up in the global scope.  I'll look into that.

**Comment by mwadams** [comment]
@Fresa  (And thanks for all these reports! Incredibly useful. Especially for working on better documentation.)
