### ISSUE TITLE
SchemaLocation might collide with properties named the same thing

### ISSUE THREAD

**Issue by Fresa** [corvus-dotnet/Corvus.JsonSchema#306]
The new `SchemaLocation` property is great, but it might collide with defined schema properties. Maybe some sort of unlikely naming convention could be used instead, or convert it to a method?

Would also be great to have it defined in a suitable interface, maybe within `IJsonValue`?

Our use case is (`T : struct, IJsonValue<T>`):
```
var schemaLocation = T.GetSchemaLocation();
var result = new JsonSchema(schemaLocation).Evaluate(jsonPayload);
if (!result.IsValid())
  throw ....
var foo = T.Parse(jsonPayload);
```

**Comment by mwadams** [comment]
I have failed to add it to the list of global exclusions which would ensure a safe name.

If I add it to the `IJsonValue<T>` interface it would a) be a breaking change and b) need to be available on all types and I'm not quite sure what I would add for e.g. JsonString etc.

I *could* add a new interface, `IGeneratedFromSchema<T>` which includes it, and add that to all the generated types?

**Comment by mwadams** [comment]
As an aside: I'm intrigued to know what you're doing in `Evaluate()`

**Comment by Fresa** [comment]
A new interface would work as well.

With a global exclusion list, to you mean that certain property names in a schema would not be supported?

We do json instance evaluation on the json payload before trying to parse it, so we know it corresponds to the defined schema. We use JsonSchema.NET for that; https://docs.json-everything.net/schema/basics/#schema-evaluation-2

**Comment by mwadams** [comment]
Oh, you don't need to do that.

Just Parse it and call IsValid() - it's WAAAAY faster than JsonSchema.NET and zero allocation.

**Comment by mwadams** [comment]
As to the global exclusion list - no, it just ensures that the property is named safely (and the documentation now tells you which json property it maps to in the underlying code)

**Comment by mwadams** [comment]
(Depending on how you are managing your json payload you may want to use `ParsedValue<T>` which gives you a disposable wrapper around your payload to avoid more allocations)

https://github.com/corvus-dotnet/Corvus.JsonSchema/blob/main/Solutions/Corvus.Json.ExtendedTypes/Corvus.Json/ParsedValue%7BT%7D.cs

**Comment by mwadams** [comment]
(We love JsonSchema.NET, BTW, but you don't need to bring both to bear on the problem.)

**Comment by Fresa** [comment]
With risk of going off topic even more, you mean `Validate` is validating the underlaying json structure according to the current json schema validation vocabularies? The [output format](https://json-schema.org/draft/2020-12/output/schema) as well?

**Comment by mwadams** [comment]
There is an overload `Validate()` that returns a ValidationContext that can capture those results if you pass a higher validation level.

We do not yet provide output from that that conforms to the Output Format schema. If you open an issue for it, though, you may be pleased with the speed with which I can close it 😁

**Comment by mwadams** [comment]
> With risk of going off topic even more, you mean `Validate` is validating the underlaying json structure according to the current json schema validation vocabularies? 

And yes, we support draft6, draft6, draft2019-09 and draft2020-12 and validate against the full Json-schema test suite.

(We need to get our Bowtie integration done so everyone can see that!)

**Comment by Fresa** [comment]
I wasn't aware of that, that's really great!
