### ISSUE TITLE
Unable to locate JSON: Issue in Generating Path

### ISSUE THREAD

**Issue by pranayjoshi** [corvus-dotnet/Corvus.JsonSchema#319]
<img width="1013" alt="Screenshot 2024-03-21 at 1 27 51 PM" src="https://github.com/corvus-dotnet/Corvus.JsonSchema/assets/35572191/45cd20ad-d362-46d6-86fe-874dc9513039">

### Steps to Recreate:
Follow the documentation
When generating the file, it will throw a JSON not found error

I tried changing the file name and file path. I also check the Absolute file path, it was exactly same as the one in the console window.

**Comment by mwadams** [comment]
On MacOS it appears to be necessary to prepend `./` to the filename. I will make address this.

**Comment by pranayjoshi** [comment]
<img width="1017" alt="Screenshot 2024-03-21 at 1 38 30 PM" src="https://github.com/corvus-dotnet/Corvus.JsonSchema/assets/35572191/5bbec7ee-0e34-4068-bd97-eeef6bc5b2c3">

**Comment by mathanraj0601** [comment]
Hi @pranayjoshi,

I've also noticed a similar issue in my laptop, so I took my friend's laptop and checked it. After successfully saving the file, the command ran smoothly on both laptops.

1. Could you please try saving the file and rerunning the command?  or
1.  Open a new terminal and rerun the command. 

It may help resolve the issue.
![image](https://github.com/corvus-dotnet/Corvus.JsonSchema/assets/98396468/5d71c1cd-4ed4-428b-8992-f42b701b102d)

**Comment by pranayjoshi** [comment]
> Hi @pranayjoshi,
> 
> I've also noticed a similar issue in my laptop, so I took my friend's laptop and checked it. After successfully saving the file, the command ran smoothly on both laptops.
> 
> 1. Could you please try saving the file and rerunning the command?  or
> 2. Open a new terminal and rerun the command.
> 
> It may help resolve the issue. ![image](https://private-user-images.githubusercontent.com/98396468/315589056-5d71c1cd-4ed4-428b-8992-f42b701b102d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNDk5NDEsIm5iZiI6MTcxMTA0OTY0MSwicGF0aCI6Ii85ODM5NjQ2OC8zMTU1ODkwNTYtNWQ3MWMxY2QtNGVkNC00MjhiLTg5OTItZjQyYjcwMWIxMDJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDE5MzQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3NzM3YTU2ZjZmMTg3NmU0ZjhjYWY5ZmNhZjczMzVjMWRlZDk3ZDlkOTdkODMzYzQ0YWYxZWIyYjQ0MThhY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M51u-cQM0Z4wBwdynhqmFEHOx9NLkIL8kdazUPJv9Nc)

Hey @mathanraj0601 , I have tried that too. It didn't work. I am trying to look for a work around. Thanks for replying.

**Comment by mathanraj0601** [comment]
> Hey @mathanraj0601 , I have tried that too. It didn't work. I am trying to look for a work around. Thanks for replying.

Anytime !

I'll keep you posted if I find any another solution

**Comment by mwadams** [comment]
Have you tried prepending `./` to the path on the commandline?

**Comment by pranayjoshi** [comment]
> Have you tried prepending `./` to the path on the commandline?

Yes I did. It didn't work

**Comment by mwadams** [comment]
Having got the netsstandard/3.0 release out of the way, I'll take a look at this.

**Comment by mwadams** [comment]
I can repro this on Ubuntu. The fix is in the associated branch.
