### ISSUE TITLE
Generated classes do not include some references

### ISSUE THREAD

**Issue by huypham0712** [corvus-dotnet/Corvus.JsonSchema#340]
My project was targeting at the latest C# language level, after running the CLI tool within the project build, I noticed that some references were not included. 

For example the `System.InvalidOperationException` were missing. 
![image](https://github.com/corvus-dotnet/Corvus.JsonSchema/assets/24435130/cc0c096c-1172-48ff-8384-936a717f081e)

I had to explicitly declare the target C# level to `12.0` and added the following settings in my project file: 
```
<ItemGroup>
	<Using Include="System" />
	<Using Include="[System.IO](http://system.io/)" />
	<Using Include="System.Collections.Generic" />
	<Using Include="System.Linq" />
</ItemGroup>
```

After that the missing references were included into the generated classes and build went ok.

**Comment by huypham0712** [comment]
@mwadams thanks for the support on this issue. 👍🏻

**Comment by mwadams** [comment]
I have moved this to #337 to capture both documentation requirements at the same time as they are closely related.
