### ISSUE TITLE
Add Type-safe EnumerateObject for additionalProperties

### ISSUE THREAD

**Issue by shuebner** [corvus-dotnet/Corvus.JsonSchema#353]
First of all, I read the blog article and think you are the only major C# JSON lib with the right approach for handling all the complexities of present day and future JSON schema.

I do have one improvement suggestion though:
the library has type-safe arrays, but not type-safe object enumeration.

Consider a schema like this:
```json
"type": "object",
"additionalProperties": {
  "type": "object",
  "properties": {
    "foo": {
      "type": "string"
    }
  }
}
```
For such a case, all of the root object's properties have to valid against the same schema.
I would like `EnumerateObject` to return a typed iterator in this case, whose `Value`s give direct access to the `foo` property.

At the moment I have to cast each `Value` with `As<>` and lose type-safety, which I then have to guard against with `IsValid`.
This trades compile-time safety for runtime safety even for simple programming errors and also requires way too much schema knowledge in the code.

Using the JSON property name as a "key" and requiring all values to adhere to the same schema is a common pattern for us.
I would much appreciate this feature.

**Comment by mwadams** [comment]
Sounds sensible to me.

One point is that you don't need to validate each item in turn, if you have validated the whole document.

But strongly typed enumeration for a fixed-type of property (i.e. a string=>type map) is a good one.

**Comment by shuebner** [comment]
>
> One point is that you don't need to validate each item in turn, if you have validated the whole document.
> 

I know. But since the compiler will not prevent me from using any ol' type for `As<>`, I have to guard against programming errors somehow. One way to do that is using `IsValid()`, That at least ensures that the expected shape of data is indeed there.

**Comment by mwadams** [comment]
This feature will be in 3.0.14 when it hits nuget in about 30 mins.
