### ISSUE TITLE
Publish snupkgs

### ISSUE THREAD

**Issue by slang25** [corvus-dotnet/Corvus.JsonSchema#355]
I see that your build is producing snupkgs, however they aren't being published to nuget.org, so they aren't easily accessible.

**Comment by slang25** [comment]
I see you've fixed this, thanks folks 🙂

**Comment by HowardvanRooijen** [comment]
Hi! Yes, something changed (I believe the default behaviour of dotnet publish), so we needed to investigate / fix that!
