### ISSUE TITLE
Will setting a property to deprecated be shown in the generated model?

### ISSUE THREAD

**Issue by challe** [corvus-dotnet/Corvus.JsonSchema#374]
A quick question that I was not able to find an answer to.
If I say that a specific property is deprecated, will this be shown in the generated model on that property?
It would very cool if it did! 😄 

Example:
```json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema", 
  "type": "object",
  "properties": {
    "my_property": {
      "type": "string",
      "deprecated": true
    }
  }
}
```

**Comment by mwadams** [comment]
It was a trivial change to add the `Obsolete` attribute to the property when it is `deprecated` in the schema.

The enhancement is just going through our CI process and will be released in the next hour or so.
