### ISSUE TITLE
Make new name generation optional

### ISSUE THREAD

**Issue by pawelmon-allclouds** [corvus-dotnet/Corvus.JsonSchema#383]
Recently introduced https://github.com/corvus-dotnet/Corvus.JsonSchema/commit/a75f2c2504422476dc7f3332771610d98a1e684e commit drastically changed the way file and type names are generated. I suggest to make this optional. You can add a new flag, e.g. `--improvedNamingHeuristics`, which would default to True, to choose new or prevoius naming convention.

**Comment by mwadams** [comment]
I'm doing a refactoring which will enable this.

**Comment by mwadams** [comment]
Fixed in #393 - please try the Preview packages on nuget.
