### ISSUE TITLE
Make generated line endings configurable

### ISSUE THREAD

**Issue by shuebner** [corvus-dotnet/Corvus.JsonSchema#391]
We work on Windows, but still have "LF" defined as line-endings in our root-level `.editorconfig` for all code files.
When I generate code with Corvus, it uses CRLF.

Please either make this configurable via command line argument, and/or (more conveniently) respect the `line_endings` setting of an `.editorconfig`, should one be in scope.

Sorry for creating issues so rapidly. It is getting real with Corvus in our project, so small things like this begin to catch our eye.

**Comment by mwadams** [comment]
Line ending configuration using the command line tool has been added in `v4.0.0-preview.21`, when it lands on NuGet.

There is a new command line option `--useUnixLineEndings` for the command line generator, and the corresponding update to the config.

I have opened #442 for adding the option to the source generator.
