### ISSUE TITLE
Allow changing IJsonValue serialization options

### ISSUE THREAD

**Issue by manekovskiy** [corvus-dotnet/Corvus.JsonSchema#437]
I use Corvus.Json to generate a fairly complex JSON documents. While these documents are sent "over the wire", there is also a need to persist some portion of this documents to the disk. In this scenario, users will look into the document to manually extract some information (as of today, the process cannot be fully automated). The IJsonValue serialization output is not indented which creates a certain level of inconvenience when reading these persisted documents.

It would be nice to be able to control the serialization options of the documents, for example, allow indented output and the maximum serialization depth. The JsonValueExtensions.Serialize extension method uses Utf8JsonWriter, so, maybe it possible to add an optional argument accepting the JsonWriterOptions? 

In the end, I don't think I care much about the shape of the public APIs exposed by Corvus.Json, for as long as I can control the output indentation and the maximum serialization depth.

**Comment by mwadams** [comment]
Although you can already use `JsonSerializer.Serialize(instance, options)` to serialize to a string with formatting, I think this is a good idea.

I have added an additional overload of the Serialize() extension method and corresponding tests. You can try it out in `v4.0.0-preview.17` when it appears on nuget.org later today.

v4 will RTM on or around November 12, 2024.

**Comment by manekovskiy** [comment]
Thank you for a quick reply and changes!
