### ISSUE TITLE
Make generated line endings pick up ambient .editorconfig settings in the SourceGenerator

### ISSUE THREAD

**Issue by mwadams** [corvus-dotnet/Corvus.JsonSchema#442]
This is a follow-up to #391 - make line endings configurable.

We would like the Source Generator to pick up line endings to emit from the ambient `.editorconfig`.

Unfortunately, this would seem to be a bit of a challenge.

https://github.com/dotnet/roslyn/issues/51437

However, what we *could* do is look at the line endings on the (first) attributed type, and emit the line ending we find there. 

I'm not too keen on that. Better would be to respect the values found in `global.editorconfig` through the usual `GlobalOptions` mechanism.

**Comment by shuebner** [comment]
I am not sure if this is really relevant.

Aren't line endings from a source generator only relevant when the generated source is checked into VCS, i. e. when the `EmitCompilerGeneratedFiles` property is set to true.
By default, it should not matter as long as the IDE supports both CRLF and LF when viewing or debugging the generated code.

**Comment by mwadams** [comment]
That's very true!
