### ISSUE TITLE
The type or namespace name 'ValidateWithoutCoreType' does not exist in the namespace 'Corvus.Json' v4.0.0-preview.20

### ISSUE THREAD

**Issue by ItsDaveB** [corvus-dotnet/Corvus.JsonSchema#443]
Firstly, what a great project! I really appreciate the hard work here, I have tested many different types of tooling for generation and this is the only one that can handle this complex large schema with extreme nesting. 

When generating the code for my specified schema, I have a few errors appearing on the latest preview version. `4.0.0-preview.20`

The type or namespace name 'ValidateWithoutCoreType' does not exist in the namespace 'Corvus.Json' _(Referenced below)_
`return Corvus.Json.ValidateWithoutCoreType.TypeInteger(value, validationContext, level, "type");`

No overload for method 'WithResult' takes 3 arguments _(Referenced below)_
`ignoredResult = ignoredResult.WithResult(isValid: true, "Validation maximum - ignored because the value is not a number", "maximum");`

**Comment by mwadams** [comment]
You need to update the reference to V4 preview Corvus.Json.ExtendedTypes in your project.

**Comment by ItsDaveB** [comment]
That was exactly it, thank you!
