### ISSUE TITLE
CorvusValidation.FormatValidationHandler is empty

### ISSUE THREAD

**Issue by ItsDaveB** [corvus-dotnet/Corvus.JsonSchema#444]
I have just performed code generation on a complex schema on version `4.0.0-preview.20`

I am getting the following error on many of the generated files, and the method is empty.
Base16.CorvusValidation.FormatValidationHandler(in AnyStakeCredential.Base16, JsonValueKind, in ValidationContext, ValidationLevel)': not all code paths return a value.

```
internal static ValidationContext FormatValidationHandler(
                    in Base16 value,
                    JsonValueKind valueKind,
                    in ValidationContext validationContext,
                    ValidationLevel level = ValidationLevel.Flag)
                {
                }
```

**Comment by ItsDaveB** [comment]
`"AnyStakeCredential":
    { "title": "AnyStakeCredential"
    , "oneOf":
      [ { "title": "Base16"
        , "description": "A stake key or script hash in base16."
        , "type": "string"
        , "contentEncoding": "base16"
        , "minLength": 56
        , "maxLength": 56
        }
      , { "title": "Bech32"
        , "type": "string"
        , "description": "A Blake2b 28-byte hash digest of a verification key or script."
        , "contentEncoding": "bech32"
        , "pattern": "^(stake_vkh|script)1[0-9a-z]*$"
        , "examples":
          [ "script1dss9g887v3rdmadpq3n44d5ph3ma4aha2rtxfdsnnftykaau8x7"
          , "stake_vkh1dss9g887v3rdmadpq3n44d5ph3ma4aha2rtxfdsnnftyklueu8u"
          ]
        }
      , { "title": "Stake Address"
        , "$ref": "cardano.json#/definitions/StakeAddress"
        }
      ]
    }`

**Comment by mwadams** [comment]
Great find! It's a bug with unrecognised content encodings.

**Comment by mwadams** [comment]
It should be a simple fix. I'll try to get it in the build tonight, and push up a new preview.

**Comment by ItsDaveB** [comment]
Much appreciated, Thanks!

**Comment by mwadams** [comment]
V4.0.0-preview.21 containing the fix for this issue is currently being indexed on nuget.org.

**Comment by ItsDaveB** [comment]
Tested again and confirmed fixed.  Thanks!
