### ISSUE TITLE
Code generator produces invalid output with empty required array in "then" block

### ISSUE THREAD

**Issue by manekovskiy** [corvus-dotnet/Corvus.JsonSchema#458]
Accidentally found an issue where code generator produces incorrect outputs when the required rule in then "block" is an empty array. The tool does not ignore the empty required block and generates an empty property name for this object "variant".

Schema:
```json
Example.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "type": "object",
  "properties": {
    "flag": {
      "type": "boolean"
    },
    "bar": {
      "type": "number"
    }
  },
  "if": {
    "properties": {
      "flag": {
        "const": true
      }
    }
  },
  "then": {
    "required": []
  },
  "else": {
    "required": [
      "bar"
    ]
  },
  "required": [
    "flag"
  ]
}
```
Command:
`generatejsonschematypes Example.json --rootNamespace "EmptyRequiredBlockIssueRepro"`

Files containing invalid code:
 - Example.Conversions.Accessors.cs
 - Example.IfThenElse.cs
 - Example.Validate.IfThenElse.cs

----
I know that the `required: []` is redundant and normally should be removed from the schema because it has no effects on the validation.

**Comment by mwadams** [comment]
Thanks for this! Will get it fixed for V4 release.

**Comment by mwadams** [comment]
This already generates correct code in V4.0.0-preview.24.
