### ISSUE TITLE
InvalidOperationException during validation

### ISSUE THREAD

**Issue by shuebner** [corvus-dotnet/Corvus.JsonSchema#467]
I get an exception during validation:

Message: 
System.InvalidOperationException : This operation does not apply to an empty instance.

Stack Trace: 
ImmutableStack`1.Peek()
ValidationContext.PushDocumentArrayIndex(Int32 arrayIndex)
MappingIntegerToString.Validate(ValidationContext& validationContext, ValidationLevel level) line 54
MappingTransform.Validate(ValidationContext& validationContext, ValidationLevel level) line 47
Transform.Validate(ValidationContext& validationContext, ValidationLevel level) line 50
TransformsArray.Validate(ValidationContext& validationContext, ValidationLevel level) line 54
VariableMappingElement.Validate(ValidationContext& validationContext, ValidationLevel level) line 50
VariableMappingArray.Validate(ValidationContext& validationContext, ValidationLevel level) line 64
Machine.Validate(ValidationContext& validationContext, ValidationLevel level) line 55
MachinesEntity.Validate(ValidationContext& validationContext, ValidationLevel level) line 50
OAC.Validate(ValidationContext& validationContext, ValidationLevel level) line 44

Validation is done with generated code.

Generator version 4.0.0-preview.24
Generator options:
--outputRootTypeName OAC
--optionalAsNullable NullOrUndefined
--disableOptionalNamingHeuristics
--useUnixLineEndings

I do not have the time to produce a minimal example, so I attached the schema and the JSON and the generated code.

[generated.zip](https://github.com/user-attachments/files/17615533/generated.zip)
[validationexception.json](https://github.com/user-attachments/files/17615534/validationexception.json)
[opcua.schema.json](https://github.com/user-attachments/files/17615541/opcua.schema.json)

The exception disappears when I remove two elements from the "mapping" array.
The whole things does not make sense to me, because why would it pop some location stack during array enumeration?

**Comment by mwadams** [comment]
I'll get this sorted today.

**Comment by mwadams** [comment]
(BTW - when your validation level is set to "Detailed" or above, we are tracking the documentation location in the validation results; that is the stack peek/push you are seeing. (I am assuming you are not validating at level `Flag` or `Basic`.)

**Comment by mwadams** [comment]
Discovered an additional call to `PopLocation()` generated when a tuple-type Array is used. We were not covering this case in the `ValidationLevel` specs.

New spec added (using the repro provided in this issue) to validate this case.

Fixed in 4.0.0-preview.25
