### ISSUE TITLE
defaultMatcher is called after successful validation

### ISSUE THREAD

**Issue by shuebner** [corvus-dotnet/Corvus.JsonSchema#468]
I assumed that after successful validation, the default matcher of a `Match` method call would never be called, at least not in case of a `oneOf`, because one of the other matcher types has to be valid.

However, I have a counter-example using 4.0.0-preview.25:

schema is again the one from #467.

this is an xunit test showing the problem

```csharp
[Fact]
public async Task Corvus_not_implemented_tests()
{
  var minimalConfig = await File.ReadAllTextAsync("samples/invalid/notimplemented.json");

  var oac = OAC.Parse(minimalConfig);
  var validationResult = oac.Validate(ValidationContext.ValidContext, ValidationLevel.Detailed);

  validationResult.IsValid.Should().BeTrue();
  var transforms = oac.Machines!.Value.SelectMany(m => m.Value.VariableMapping.SelectMany(m => m.Transforms!.Value));
  var valueOverrideTransforms = transforms.Select(t => t.ValueOverride).Where(o => o.HasValue).Select(o => o.Value);
  var hasCalledDefaultMatcher = valueOverrideTransforms.Select(t => t.Condition.Value.Match(
    (in OAC.ValueOverrideTransform.ConditionEntity.ValueEntity.OneOf0Array a0) => false,
    (in OAC.ValueOverrideTransform.ConditionEntity.ValueEntity.OneOf1Array a1) => false,
    (in OAC.ValueOverrideTransform.ConditionEntity.ValueEntity def) => true));

  hasCalledDefaultMatcher.Should().NotContain(true);
}
```

Schema and the notimplemented.json sample is attached.
[opcua.schema.json](https://github.com/user-attachments/files/17619399/opcua.schema.json)
[notimplemented.json](https://github.com/user-attachments/files/17619402/notimplemented.json)

**Comment by mwadams** [comment]
Investigating.

Top tip: always validate with `ValidationLevel.Flag` and if you get a validation failure and need details, validate *again* with the more detailed validation results. It is way, way faster for the normal 'IsValid` case.

**Comment by mwadams** [comment]
Thanks for reporting this! It's a bona-fide code gen bug. The schema should *not* be valid, and it validating "true" because we are failing to create a child context and merge back when doing additional properties validation.

It's interesting that this is not a case caught by the json-schema test suite.

**Comment by mwadams** [comment]
This will be fixed in V4.0.0-preview.26

**Comment by mwadams** [comment]
(Note that your `notimplemented.json` instance is *not* valid according to the schema.

**Comment by shuebner** [comment]
Thank you for providing these quick fixes. It makes us confident in our choice of Corvus, despite its relative newness and preview versions.

> It's interesting that this is not a case caught by the json-schema test suite.

That's what I thought as well. 10k+ tests but a fairly trivial case like this seems to not be covered...

> Note that your `notimplemented.json` instance is _not_ valid according to the schema.

I know. That is how we discovered the bug. The code using the generated POCOs and the `Match` method should not even have run, because it only runs when the JSON is valid against the schema.
