### ISSUE TITLE
Add --version option to generatejsonschematypes

### ISSUE THREAD

**Issue by michaelmior** [corvus-dotnet/Corvus.JsonSchema#475]
It would be really helpful if `generatejsonschematypes` had a `--version` option to be able to quickly see what version of the tool is installed.

**Comment by mwadams** [comment]
As of `4.0.0-preview.32` 

```
generatejsonschematypes version
```

produces

```
Version: 4.0.0-preview.32 Build: ce4cb9b9ef77f3004673b69a8f44b36850eb919d
```

**Comment by michaelmior** [comment]
@mwadams Thanks!
