### ISSUE TITLE
Upper case characters in email address

### ISSUE THREAD

**Issue by SJones-CTC** [corvus-dotnet/Corvus.JsonSchema#481]
The regex CreateEmailPattern in Validate.cs does not allow for upper case characters in email addresses. This results in IsValid returning False with a ValidationResult of:
"Invalid Validation 6.1.1 type - should have been 'string' with format 'email', but was 'Endjin@corvus.net'."
This is for a json schema with "type": "string", "format": "email"

**Comment by mwadams** [comment]
Just got time to slip this into a final preview before we ship, if you'd like to test v4.0.0-preview.35 when it lands in an hour or so.

**Comment by SJones-CTC** [comment]
I can confirm that this works for me in v4.0.0-preview.35. Thanks for the fix!
