### ISSUE TITLE
Corvus.Json.SourceGenerator generate Nullable types resulting in a compiler error.

### ISSUE THREAD

**Issue by moomiji** [corvus-dotnet/Corvus.JsonSchema#492]
Corvus.Json.SourceGenerator generates Nullable types resulting in a compiler error [CS0453](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0453).

- schema
```json
{
    "$schema": "https://json-schema.org/draft-07/schema",
    "type": "object",
    "dependencies": {
        "recognition": { }
    }
}
```
- error
```
Restore complete (0.5s)
  Repro492 failed with 1 error(s) (0.8s)
    _\Corvus.Json.SourceGenerator\Corvus.Json.SourceGenerator.IncrementalSourceGenerator\PipelineSchema.Object.g.cs(695,30): error CS0453: The type 'JsonAny?' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'JsonValueExtensions.IsNotUndefined<T>(T)'
```

This is because `static void SomeExtensionMethods<T>(this T value) where T : struct`, is used directly for nullable types generated by the source generator.

The two available solutions are as follows:
- Not generating nullable types, similarly to the behaviour in Corvus.Json.JsonSchema.TypeGeneratorTool.
- Overload methods `static void OverloadExtensionMethods<T>(this Nullable<T> value) where T : struct`

This is the Minimum Repro Project: [Repro492.zip](https://github.com/user-attachments/files/17808389/Repro492.zip)

BTW: The two full schema I used are here: [pipeline.schema.json](https://raw.githubusercontent.com/MaaXYZ/MaaFramework/refs/heads/main/tools/pipeline.schema.json), [interface.schema.json](https://raw.githubusercontent.com/MaaXYZ/MaaFramework/refs/heads/main/tools/interface.schema.json).

**Comment by mwadams** [comment]
It is "by design" that the initial implementation of the SourceGenerator generates code with nullable types for optional properties. Configuration for this will be provided in later versions.

However, there is a generation bug when generating code for dependent schemas combined with nullable types. I have updated the title of this to reflect that issue.

**Comment by mwadams** [comment]
I had also failed to pack the .props file with the SourceGenerator. Once you have updated to 4.0.10 you have the following global configuration for the SourceGenerator:

To disable the optional as nullable behaviour, add the following to your .csproj file

```xml
 <PropertyGroup>
     <CorvusJsonSchemaOptionalAsNullable>None</CorvusJsonSchemaOptionalAsNullable>
 </PropertyGroup>
```

The configuration options have been added to the README but are reproduced here for convenience.

#### Configuring the source generator

There are a number of global configuration options for the source generator. These can be added to a `PropertyGroup` in your `.csproj` file.

e.g.

```xml
<PropertyGroup>
   <CorvusJsonSchemaOptionalAsNullable>None</CorvusJsonSchemaOptionalAsNullable>
</PropertyGroup>
```

`CorvusJsonSchemaOptionalAsNullable`
  - `None` - Do not emit nullable properties for optional properties
  - `NullOrUndefined` - Emit nullable properties for optional properties

`CorvusJsonSchemaDisableOptionalNamingHeuristics`
  - `False` - Enable optional naming heuristics [default]
  - `True` - Disable optional naming heuristics

`CorvusJsonSchemaDisabledNamingHeuristics`
  - Semi-colon separated list of naming heuristics to disable. You can list the available name heuristics with the `generatejsonschematypes listNameHeuristics` command in the CLI.

`CorvusJsonSchemaAlwaysAssertFormat`
  - `False` - Respect the vocabulary's format assertion
  - `True` - Always assert format assertions [default]
