### ISSUE TITLE
Generated code should include all required using statements

### ISSUE THREAD

**Issue by shuebner** [corvus-dotnet/Corvus.JsonSchema#514]
In 4.1.0, the generated code relies on some stdlib types being available, like `Stream`, `ReadOnlyMemory`, `IDictionary` etc. without having a `using` statement for the corresponding namespaces.

This means that the generated code only compiles if the consuming project sets global usings for those namespaces, e. g. by declaring `Microsoft.NET.Sdk` as the project SDK and setting `ImplicitUsings` to true.

Generated code should IMHO not put this burden on the consumer (and restrict consumers to a C# version where global usings are available in the first place).
Please generate the necessary using statements in the code requiring them.

**Comment by mwadams** [comment]
If we do generate those usings, then you get warnings for the duplicate usings in what is the default situation when you do a`dotnet new` or new project. We decided to default to the "do not add usings" case.

However, there is no reason this could not be another option.

I'll add that.
