### ISSUE TITLE
JsonAny.UndefinedHashCode relies on permanent stability of GetHashCode

### ISSUE THREAD

**Issue by idg10** [corvus-dotnet/Corvus.JsonSchema#53]
Although .NET requires that `GetHashCode` returns the same result for any two instances of a type that are equal, in general this is guaranteed only for the lifetime of a process. Two different processes can (and for some .NET runtime library types, will) return different hash codes for the same value.

That makes this line a problem:

https://github.com/corvus-dotnet/Corvus.JsonSchema/blob/b563a2aad0ed12712db252ad7bc368f7d62daf8b/Solutions/Corvus.Json.ExtendedTypes/Corvus.Json/JsonAny.cs#L21

The reason hash codes are not necessarily stable across process restarts is that back when they used to be, hackers worked out this could be used to amplify denial of service attacks against code using dictionaries and other hash table based data structures. The most significant change Microsoft made to address this was to make `string` change its hash code over time.

You can see that with this test program:

```cs
Console.WriteLine("Hello, World!".GetHashCode());
Console.WriteLine("Hello, World!".GetHashCode());
```

On any single execution this will print out the same number twice, but it can (and does) change that number between runs:

```
C:\temp\ChangingHash
❯ dotnet run -c Release
1205934647
1205934647
C:\temp\ChangingHash
❯ dotnet run -c Release
729728354
729728354
C:\temp\ChangingHash
❯ dotnet run -c Release
-835583673
-835583673
```

It's true that in .NET 6.0, `Guid.GetHashCode` appears always to return the same value for the same input, even across process boundaries. But I don't see that documented anywhere, so we probably shouldn't rely on it.

**Comment by mwadams** [comment]
Part of this could be addressed by changing the comment to "happens to be the hashcode of that GUID on the day I wanted a hashcode that wouldn't be for anything else that might actually get used".

The other part - the attack vector - is more pertinent.

Perhaps we should use `ValueKind.Undefined.GetHashCode()` opaquely. Or `static readonly` a `"Corvus.Undefined".GetHashCode()`

**Comment by mwadams** [comment]
(To clarify this point - I dispute the title. It *doesn't* rely on permanent stability, but, like `Guid` it currently *happens to be* permanently stable which may be an issue.)

**Comment by idg10** [comment]
I think it's possible I misunderstood the purpose of the comment. I though the reason it mentioned how you'd got that particular number is that its relationship with that `Guid` was somehow significant.

If it just said "This is a number chosen arbitrarily that has a good chance of being different from the hash for any commonly used value" then I wouldn't have commented.

**Comment by mwadams** [comment]
However, having read more about it and looked at how the new hashcode stuff works from a random seed (as per the internal Marvin bits for string hashcodes) I take advantage of that in the new implementation of this stuff.

I was also unaware that `null` hashes to 0 which seems to encourage very bad behaviour.
